import { PostData } from "@/components/feed/InstagramPost";

const MOCK_AVATARS = [
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
];

const MOCK_IMAGES = [
  "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=750&fit=crop",
  "https://images.unsplash.com/photo-1553729459-uj1ef3173491?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=600&h=600&fit=crop",
  "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&h=750&fit=crop",
];

export const MOCK_FEED_POSTS: PostData[] = [
  {
    id: "mock-1",
    content: "🚀 Resultado do mês com TikTok Shop! Comecei do zero e já atingi R$12.400 em comissões. A chave foi consistência + conteúdo autêntico. Quem quer aprender?",
    postType: "image",
    mediaUrl: MOCK_IMAGES[0],
    likesCount: 2847,
    commentsCount: 342,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    userId: "mock-user-1",
    isLiked: false,
    isSaved: false,
    label: "verified_result",
    labelMetadata: { amount: 12400, period: "mês", clicks: 8920, views: 145000 },
    profile: {
      username: "marinasales",
      displayName: "Marina Sales",
      avatarUrl: MOCK_AVATARS[0],
      isVerified: true,
      totalEarnings: 87500,
    },
    affiliateLink: {
      url: "https://example.com/ref/marina",
      productName: "Curso Afiliado Pro",
      commission: 40,
    },
  },
  {
    id: "mock-2",
    content: "Quem disse que TikTok é só dancinha? 💰 Minha loja no TikTok Shop bateu 500 vendas esse mês. Produto certo + público certo = resultado garantido.",
    postType: "image",
    mediaUrl: MOCK_IMAGES[1],
    likesCount: 1523,
    commentsCount: 189,
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    userId: "mock-user-2",
    isLiked: true,
    isSaved: false,
    label: "active_offer",
    labelMetadata: { product_name: "Kit Skincare Glow", commission_percent: 25, offer_url: "#" },
    profile: {
      username: "pedroaffiliate",
      displayName: "Pedro Henrique",
      avatarUrl: MOCK_AVATARS[1],
      isVerified: true,
      totalEarnings: 45200,
    },
    affiliateLink: {
      url: "https://example.com/ref/pedro",
      productName: "Kit Skincare Glow",
      commission: 25,
    },
  },
  {
    id: "mock-3",
    content: "O segredo dos top afiliados: não é sobre o produto, é sobre a narrativa. Cada vídeo que posto conta uma história real. Resultado? CTR de 8.2% e crescendo 📈",
    postType: "text",
    likesCount: 956,
    commentsCount: 87,
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    userId: "mock-user-3",
    isLiked: false,
    isSaved: true,
    profile: {
      username: "juliacreator",
      displayName: "Julia Creator",
      avatarUrl: MOCK_AVATARS[2],
      isVerified: true,
      totalEarnings: 32100,
    },
  },
  {
    id: "mock-4",
    content: "PATROCINADO 🤝 Parceria oficial com a NovaSkin! Testei o sérum por 30 dias e os resultados são reais. Link na bio com 15% OFF exclusivo pra vocês!",
    postType: "image",
    mediaUrl: MOCK_IMAGES[2],
    likesCount: 3201,
    commentsCount: 456,
    createdAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    userId: "mock-user-4",
    isLiked: false,
    isSaved: false,
    label: "sponsored",
    labelMetadata: { brand_name: "NovaSkin", commission_percent: 15 },
    profile: {
      username: "rafadigital",
      displayName: "Rafa Digital",
      avatarUrl: MOCK_AVATARS[3],
      isVerified: true,
      totalEarnings: 120000,
    },
    affiliateLink: {
      url: "https://example.com/ref/rafa",
      productName: "Sérum NovaSkin",
      commission: 15,
    },
  },
  {
    id: "mock-5",
    content: "Primeiro mês como afiliada e já tirei R$2.100! 🎉 Nunca imaginei que vídeos curtos podiam gerar tanta receita. Obrigada comunidade!",
    postType: "image",
    mediaUrl: MOCK_IMAGES[4],
    likesCount: 1890,
    commentsCount: 234,
    createdAt: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    userId: "mock-user-5",
    isLiked: false,
    isSaved: false,
    label: "verified_result",
    labelMetadata: { amount: 2100, period: "mês", clicks: 3400, views: 52000 },
    profile: {
      username: "beatriznova",
      displayName: "Beatriz Nova",
      avatarUrl: MOCK_AVATARS[4],
      isVerified: false,
    },
  },
  {
    id: "mock-6",
    content: "Dica de ouro: use o TikTok Shop Analytics pra encontrar os horários de pico do seu público. Meu engajamento subiu 3x depois que ajustei os horários de postagem ⏰",
    postType: "image",
    mediaUrl: MOCK_IMAGES[5],
    likesCount: 743,
    commentsCount: 92,
    createdAt: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    userId: "mock-user-6",
    isLiked: true,
    isSaved: false,
    profile: {
      username: "lucasmarketing",
      displayName: "Lucas Marketing",
      avatarUrl: MOCK_AVATARS[5],
      isVerified: true,
      totalEarnings: 67800,
    },
  },
];

export const MOCK_STORIES = [
  { userId: "mock-user-1", username: "marinasales", displayName: "Marina Sales", avatarUrl: MOCK_AVATARS[0], hasNew: true },
  { userId: "mock-user-2", username: "pedroaffiliate", displayName: "Pedro H.", avatarUrl: MOCK_AVATARS[1], hasNew: true },
  { userId: "mock-user-3", username: "juliacreator", displayName: "Julia", avatarUrl: MOCK_AVATARS[2], hasNew: true },
  { userId: "mock-user-4", username: "rafadigital", displayName: "Rafa", avatarUrl: MOCK_AVATARS[3], hasNew: false },
  { userId: "mock-user-5", username: "beatriznova", displayName: "Bia", avatarUrl: MOCK_AVATARS[4], hasNew: true },
  { userId: "mock-user-6", username: "lucasmarketing", displayName: "Lucas", avatarUrl: MOCK_AVATARS[5], hasNew: false },
];
